import warnings
with warnings.catch_warnings():
    warnings.filterwarnings("ignore",category=FutureWarning)
    import h5py
import numpy as np
import matplotlib.pyplot as plt  
plt.close('all')

f = h5py.File('headct.h5', 'r')
det=f.get('det')
det=np.transpose(det)
detector=np.load('Detector.npy')
plt.figure(1)
plt.imshow(det, extent=[0, 200, 0, 200])
plt.title('Detector Image Matlab')
plt.xlabel('X Pixel')
plt.ylabel('Y Pixel')
plt.colorbar()
plt.figure(2)
plt.imshow(detector, extent=[0, 200, 0, 200])
plt.title('Detector Image Python')
plt.xlabel('X Pixel')
plt.ylabel('Y Pixel')
plt.colorbar()
plt.figure(3)
plt.imshow(np.log(det), extent=[0, 200, 0, 200])
plt.title('Detector Log Image Matlab')
plt.xlabel('X Pixel')
plt.ylabel('Y Pixel')
plt.colorbar()
plt.figure(4)
plt.imshow(np.log(detector), extent=[0, 200, 0, 200])
plt.title('Detector Log Image Python')
plt.xlabel('X Pixel')
plt.ylabel('Y Pixel')
plt.colorbar()
plt.show()
